# Generated by Django 3.0.6 on 2020-05-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0002_ratingdummy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={"verbose_name_plural": "faculties",},
        ),
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_helper.Faculty",
            ),
        ),
    ]
