# Generated by Django 3.0.6 on 2020-05-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0003_auto_20200527_1531"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOccurrence",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField(choices=[(1, "A"), (2, "B"), (3, "C"), (4, "Summer"), (5, "Yearly")])),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.Course")),
            ],
            options={"unique_together": {("course", "year", "semester")},},
        ),
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial_number", models.IntegerField()),
                ("lecturer", models.CharField(max_length=100)),
                ("class_type", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=50)),
                ("day", models.CharField(max_length=30)),
                ("hour", models.CharField(max_length=30)),
                ("hall", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academic_helper.CourseOccurrence"
                    ),
                ),
            ],
        ),
    ]
