# Generated by Django 3.0.6 on 2020-05-30 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0004_courseclass_courseoccurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "campuses",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="courseclass",
            options={"verbose_name_plural": "course classes"},
        ),
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="courseclass",
            name="class_type",
        ),
        migrations.RemoveField(
            model_name="courseclass",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseclass",
            name="hour",
        ),
        migrations.RemoveField(
            model_name="courseclass",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="courseclass",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="courseclass",
            name="end_time",
            field=models.TimeField(default="12:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseclass",
            name="semester",
            field=models.IntegerField(
                blank=True, choices=[(1, "A"), (2, "B"), (3, "C"), (4, "Summer"), (5, "Yearly")], null=True
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="start_time",
            field=models.TimeField(default="11:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courseoccurrence",
            name="credits",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="course_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Sunday"),
                    (2, "Monday"),
                    (3, "Tuesday"),
                    (4, "Wednesday"),
                    (5, "Thursday"),
                    (6, "Friday"),
                    (7, "Saturday"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "campus",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_helper.Campus"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "class_type",
                    models.IntegerField(
                        choices=[
                            (1, "Lecture"),
                            (2, "Recitation"),
                            (3, "Seminar"),
                            (4, "Lab"),
                            (5, "Workshop"),
                            (6, "Assignment"),
                            (7, "Clinical"),
                            (8, "Trip"),
                            (9, "Preparatory"),
                            (10, "Guidance"),
                            (11, "Guidance And Lecture"),
                        ]
                    ),
                ),
                ("mark", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academic_helper.CourseOccurrence"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="courseclass",
            name="teacher",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_helper.Teacher"
            ),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.ClassGroup"),
        ),
        migrations.AlterField(
            model_name="courseclass",
            name="hall",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_helper.Hall"
            ),
        ),
    ]
