# Generated by Django 3.0.6 on 2020-06-02 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_auto_20200602_1856"),
        ("account", "0003_auto_20200602_1856"),
        ("admin", "0004_auto_20200602_1856"),
        ("star_ratings", "0004_auto_20200602_1856"),
        ("socialaccount", "0004_auto_20200602_1856"),
        ("auth", "0011_update_proxy_permissions"),
        ("academic_helper", "0006_auto_20200531_1534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedcourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field="id"
            ),
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.ClassGroup"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
    ]
