# Generated by Django 3.0.6 on 2020-06-02 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0006_auto_20200531_1534"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.ClassGroup"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
    ]
