# Generated by Django 3.0.6 on 2020-06-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0007_classschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="faculty",
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "faculty",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.Faculty"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="academic_helper.School"
            ),
        ),
    ]
