# Generated by Django 3.0.7 on 2020-06-29 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("academic_helper", "0009_auto_20200628_0038"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeProgram",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("code", models.IntegerField()),
                ("credits", models.IntegerField()),
                ("is_public", models.BooleanField(default=True)),
                ("blocks", models.ManyToManyField(to="academic_helper.StudyBlock")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="UserCourseChoice",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.StudyBlock"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academic_helper.CourseOccurrence"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("user", "course")},},
        ),
        migrations.RenameModel(old_name="School", new_name="Department",),
        migrations.RemoveField(model_name="studyplan", name="blocks",),
        migrations.RenameField(model_name="course", old_name="school", new_name="department",),
        migrations.DeleteModel(name="CompletedCourse",),
        migrations.DeleteModel(name="StudyPlan",),
    ]
