# Generated by Django 3.0.7 on 2020-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_helper', '0010_auto_20200629_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(to='academic_helper.Teacher'),
        ),
    ]
