# Generated by Django 3.0.7 on 2020-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0011_auto_20200709_1858"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseclass",
            name="notes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="special_occurrence",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseoccurrence",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
