# Generated by Django 3.0.7 on 2020-07-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_helper', '0011_classgroup_teachers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('occurrence', 'class_type', 'mark')},
        ),
    ]
