# Generated by Django 3.0.7 on 2020-08-13 23:31

import django.db.models.deletion
from django.db import migrations, models

from academic_helper.models import University, Course, Faculty
from academic_helper.utils.logger import log, wrap


def handle_uni_default(apps, schema_editor):
    log.info(f"Creating default university")
    def_uni = University(name="Default university", english_name="Default university", abbreviation="DU")
    def_uni.save()
    for course in Course.objects.all().values("id", "university_id"):
        if not course.university_id:
            log.info(f"Changing university for course {wrap(course.id)}")
            course.university = def_uni
            course.save()
        else:
            log.info(f"Course {wrap(course.id)} already had university: ${wrap(course.university)}")
    for faculty in Faculty.objects.all():
        if not faculty.university_id:
            log.info(f"Changing university for faculty {wrap(faculty.id)}")
            faculty.university = def_uni
            faculty.save()
        else:
            log.info(f"Faculty {wrap(faculty.id)} already had university: ${wrap(faculty.university)}")


class Migration(migrations.Migration):
    dependencies = [
        ("academic_helper", "0014_auto_20200814_0226"),
    ]

    operations = [
        migrations.RunPython(handle_uni_default),
        migrations.AlterField(
            model_name="course",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.University"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.University"),
        ),
    ]
