# Generated by Django 3.0.7 on 2020-08-13 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_helper", "0014_auto_20200814_0226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.University"),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="university",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="academic_helper.University"),
        ),
    ]
