# Generated by Django 3.0.7 on 2020-08-14 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academic_helper", "0015_auto_20200814_0231"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"verbose_name_plural": "Universities"},
        ),
    ]
