# Generated by Django 3.0.7 on 2020-08-14 08:53

from django.db import migrations, models

from academic_helper.models.course_occurrence import CourseOccurrence


def move_names(apps, schema_editor):
    for occurrence in CourseOccurrence.objects.all():
        occurrence.name = occurrence.course.name
        occurrence.save()


class Migration(migrations.Migration):
    dependencies = [
        ("academic_helper", "0016_auto_20200814_0317"),
    ]

    operations = [
        migrations.RenameField(model_name="course", old_name="name", new_name="_name"),
        migrations.AlterField(
            model_name="course", name="_name", field=models.CharField(max_length=150, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseoccurrence", name="name", field=models.CharField(max_length=150, default="-"),
        ),
        migrations.AlterModelOptions(
            name="courseoccurrence", options={"ordering": ["course__course_number", "year", "semester"]},
        ),
        migrations.RunPython(move_names),
    ]
