# Generated by Django 3.1.7 on 2021-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_helper", "0017_auto_20200814_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursistuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
