# Generated by Django 3.0.6 on 2020-05-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_number", models.CharField(max_length=30, unique=True)),
                ("name_he", models.CharField(max_length=300)),
                ("name_en", models.CharField(max_length=300)),
                ("year", models.IntegerField()),
                ("semester", models.CharField(max_length=30)),
                ("nz", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_number", models.CharField(max_length=30)),
                ("serial_number", models.IntegerField()),
                ("lecturer", models.CharField(max_length=300)),
                ("class_type", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=30)),
                ("semester", models.CharField(max_length=100)),
                ("day", models.CharField(max_length=30)),
                ("hour", models.CharField(max_length=100)),
                ("hall", models.CharField(max_length=300)),
                ("course_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schedule.Course")),
            ],
        ),
    ]
