# Generated by Django 3.0.6 on 2020-05-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="course", name="name_en", field=models.CharField(max_length=100),),
        migrations.AlterField(model_name="course", name="name_he", field=models.CharField(max_length=100),),
    ]
