# Generated by Django 3.0.7 on 2020-06-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecomment",
            name="semester",
            field=models.IntegerField(
                blank=True, choices=[(1, "A"), (2, "B"), (3, "C"), (4, "Summer"), (5, "Yearly")], null=True
            ),
        ),
        migrations.AddField(model_name="coursecomment", name="year", field=models.IntegerField(blank=True, null=True),),
        migrations.AlterField(
            model_name="coursecomment",
            name="is_anonymous",
            field=models.BooleanField(
                default=False, help_text="Check this box if we should hide the user name.", verbose_name="is anonymous"
            ),
        ),
    ]
