# Generated by Django 3.0.7 on 2020-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecomment",
            name="semester",
            field=models.CharField(blank=True, max_length=10, verbose_name="semester"),
        ),
        migrations.AddField(
            model_name="coursecomment",
            name="year",
            field=models.CharField(blank=True, max_length=10, verbose_name="year"),
        ),
        migrations.AlterField(
            model_name="coursecomment",
            name="is_anonymous",
            field=models.BooleanField(
                default=False, help_text="Check this box if we should hide the user name.", verbose_name="is anonymous"
            ),
        ),
    ]
