# Generated by Django 3.0.7 on 2020-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecomment",
            name="show_email",
            field=models.BooleanField(
                default=True, help_text="Check this box if we should show the email address.", verbose_name="show email"
            ),
        ),
    ]
