# Generated by Django 3.0.6 on 2020-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="course", name="course_number", field=models.IntegerField(unique=True),),
        migrations.AlterField(model_name="course", name="title", field=models.CharField(max_length=100, unique=True),),
    ]
