name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: app.settings
    steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Run mirgations
        run: |
          python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test academic_helper

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check black formatting
        uses: lgeiger/black-action@master
        with:
          args: '. -l 120 --exclude ".*/node_modules/.*" --check'
